# Generated by Django 2.0.4 on 2018-05-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('school', models.CharField(blank=True, max_length=30)),
                ('major', models.CharField(blank=True, max_length=30)),
                ('teacher', models.CharField(blank=True, max_length=20)),
                ('credit', models.FloatField(default=1.0)),
                ('start_week', models.IntegerField(blank=True, default=0)),
                ('end_week', models.IntegerField(blank=True, default=0)),
                ('gap', models.IntegerField(blank=True, default=0)),
                ('day_in_week', models.IntegerField(blank=True, default=0)),
                ('start_time', models.IntegerField(blank=True, default=0)),
                ('end_time', models.IntegerField(blank=True, default=0)),
                ('area', models.IntegerField(blank=True, default=0)),
                ('building', models.CharField(default=0, max_length=4)),
                ('room', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
