# Generated by Django 2.0.4 on 2018-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='data_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='allcourses',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
