# Generated by Django 2.0.4 on 2018-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180506_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='building',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
