# Generated by Django 2.0.4 on 2018-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180506_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='area',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='allcourses',
            name='building',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='allcourses',
            name='room',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
