# Generated by Django 2.0.4 on 2018-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_pushmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushmessage',
            name='course_place',
        ),
        migrations.RemoveField(
            model_name='pushmessage',
            name='course_time',
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='area',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='begin_hour',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='begin_minute',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='building',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='end_hour',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='end_minute',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pushmessage',
            name='room',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
