# Generated by Django 2.0.6 on 2018-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20180517_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='art',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='communication',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='internation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='leader',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='logic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='others',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='science',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='allcourses',
            name='society',
            field=models.FloatField(default=0.0),
        ),
    ]
