# Generated by Django 2.0.4 on 2018-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuser',
            name='sigh',
            field=models.CharField(default='I am goo!', max_length=100),
        ),
    ]
