# Generated by Django 2.0.4 on 2018-05-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180507_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
    ]
