# Generated by Django 2.0.4 on 2018-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180512_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehistory',
            name='comment',
            field=models.CharField(default='写点什么吧！', max_length=200),
        ),
    ]
